"""
Backlog Promoter Service — CB-2384 Studio Phase 1 Stub

Placeholder for the full Blueprint promote state machine.  In Phase 1 the
``start_promote`` coroutine simply waits 100 ms and writes a PROMOTE_DONE
BacklogActivity row, giving the polling endpoint something to return.

The real pipeline (Phase 2+) will:
  1. Validate the BacklogItem against the tenant project.
  2. Call the AI hierarchy-generation endpoint.
  3. Push the resulting FEATURE/EPIC/STORY/TASK tree to CodeBoard.
  4. Optionally enqueue the FEATURE in the AutoPilot queue.
  5. Write incremental PROMOTE_STAGE / PROMOTE_ISSUE_CREATED events.
  6. Write PROMOTE_DONE (success) or PROMOTE_FAILED + rollback.

Callers must NOT await this directly — launch it as a fire-and-forget task:

    asyncio.ensure_future(start_promote(item_id, job_id, db_factory))

The function opens its own database session so it is safe to use after the
request-scoped session has been committed and closed.
"""

from __future__ import annotations

import asyncio
import logging
import uuid

logger = logging.getLogger(__name__)


async def start_promote(item_id: str, job_id: str, _db=None) -> None:
    """Phase 1 stub: write PROMOTE_DONE after a short delay.

    Opens a fresh database session so this coroutine is decoupled from the
    caller's request-scoped session lifetime.

    Args:
        item_id: The BacklogItem.id being promoted.
        job_id: The promoteJobId generated by the promote endpoint.
        _db: Ignored in Phase 1; kept in signature for Phase 2 compatibility.
    """
    try:
        await asyncio.sleep(0.1)  # 100ms stub delay

        from models.database import AsyncSessionLocal
        from models.backlog import BacklogActivity

        async with AsyncSessionLocal() as session:
            activity = BacklogActivity(
                id=str(uuid.uuid4()),
                tenantId=None,  # inherit from item context in Phase 2
                itemId=item_id,
                action="PROMOTE_DONE",
                payload={"promoteJobId": job_id, "stub": True},
                actor="system",
                # onupdate=func.now() handles updatedAt automatically.
            )
            session.add(activity)
            await session.commit()

        logger.info(
            "backlog_promoter: stub PROMOTE_DONE written for item=%s job=%s",
            item_id,
            job_id,
        )
    except Exception as exc:  # noqa: BLE001
        logger.error(
            "backlog_promoter: failed to write PROMOTE_DONE for item=%s job=%s: %s",
            item_id,
            job_id,
            exc,
        )
