#!/usr/bin/env python3
"""CB-2793 QA-gate remediation — file 8 BUGs under CB-2793, re-rank CB-2801/2802.

Generated by Jonny (VP R&D) after the CB-2793 COMPLETED_WAITING_QA gate FAILED:
backend tests 180 pass / 1 fail, code-reviewer 2 HIGH, security-auditor 2 HIGH.
"""
import json
import urllib.request

API = "http://localhost:8401/api"
PROJECT = "1511e54f71dccd3fa79f67fe"
CB2793 = "94c01b1d-47f4-4ef6-813f-2aec497bb581"
CB2801 = "da6a694d-869e-432c-b87d-75b942526ff8"
CB2802 = "43630eeb-2918-40a8-a8f2-715b6c5176fa"
LABEL = "cb-2793-qa-remediation"


def post(path, payload):
    req = urllib.request.Request(
        f"{API}{path}",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
        method="POST",
    )
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())


def patch(path, payload):
    req = urllib.request.Request(
        f"{API}{path}",
        data=json.dumps(payload).encode(),
        headers={"Content-Type": "application/json"},
        method="PATCH",
    )
    with urllib.request.urlopen(req) as r:
        return json.loads(r.read())


BUGS = [
    {
        "title": "B1 — off-by-one defeats circuit-breaker abort recommendation",
        "priority": "HIGH",
        "description": (
            "## QA finding (code-reviewer HIGH)\n\n"
            "`api/execution.py:1070` `_suggested_action` uses `auto_resume_attempts "
            "> _AUTO_RESUME_MAX_ATTEMPTS`. Every other site was changed to `>=` in S1 "
            "(CB-2794). When the breaker trips the counter stays at MAX (3), so `3 > 3` "
            "is False and recovery-status returns `suggested_action='resume'`. The "
            "AutoPilotRecoveryBanner then shows a green 'Resume now' button instead of "
            "'Abort' for exactly the runaway-token-burn scenario S2 (CB-2795) exists to "
            "stop.\n\n## Fix\nChange `>` to `>=` at `execution.py:1070`. Add a unit test "
            "asserting suggested_action=='abort' when attempts==MAX."
        ),
    },
    {
        "title": "B2 — state machine rejects idempotent self-edges (running->running)",
        "priority": "HIGH",
        "description": (
            "## QA finding (code-reviewer HIGH)\n\n"
            "`models/autopilot.py` `_ALLOWED_TRANSITIONS` has no self-edges. After a "
            "swallowed DB-write failure leaves in-memory status at RUNNING, the "
            "resume-after-pause path calls `_transition(RUNNING)` => `running->running` "
            "=> `IllegalStateTransitionError`. `clear_recovery_state` already carries a "
            "`paused->paused` special-case workaround — a symptom of this gap. Violates "
            "S4's (CB-2797) own 'do not swallow IllegalStateTransitionError' contract.\n\n"
            "## Fix\nTreat `from == to` as a no-op success in `is_transition_allowed` "
            "(or add explicit self-edges). Remove the clear_recovery_state workaround. "
            "Unit test each self-edge."
        ),
    },
    {
        "title": "B5 — failing test: CB-2792 systemic-window constant not reconciled with S6",
        "priority": "HIGH",
        "description": (
            "## QA finding (failing test)\n\n"
            "S6 (CB-2799) changed `_SYSTEMIC_FAILURE_WINDOW_SECONDS` 60.0 -> 1800.0. "
            "`tests/test_cb2792_systemic_failure.py::test_threshold_constant_matches_design` "
            "still asserts `== 60.0` => suite is RED (180 pass, 1 fail). The CB-2793 "
            "commit message claims '157 passed' — the failing file was either excluded "
            "or committed knowingly red.\n\n## Fix\nReconcile the test with the "
            "consecutive-failures design from CB-2799 (update or remove the stale "
            "duration-window assertion). Verify the full AutoPilot suite is green."
        ),
    },
    {
        "title": "M1 — recovery banner 'retry-failed' calls plain /resume, not retry_failed=true",
        "priority": "MEDIUM",
        "description": (
            "## QA finding (code-reviewer / security MEDIUM)\n\n"
            "`AutoPilotRecoveryBanner.tsx:~496` maps the `retry-failed` action to a plain "
            "`POST /resume`. S3 (CB-2796) shipped `reset-failed-tasks` and "
            "`resume?retry_failed=true` precisely for this; AutoPilotFloatingBar uses "
            "them but the banner does not. A queue with only failed+completed tasks gets "
            "a 409 the banner silently swallows (`if (res.ok)` only). Headline feature "
            "unreachable from one of its two UIs.\n\n## Fix\nBanner -> "
            "`resume?retry_failed=true`; surface 409 to the user."
        ),
    },
    {
        "title": "M2 — transition_state nulls pauseReason on every non-pause transition",
        "priority": "MEDIUM",
        "description": (
            "## QA finding (code-reviewer MEDIUM)\n\n"
            "`utils/autopilot_repository.py` `transition_state` writes "
            "`record.pauseReason = new_reason`; for running/completed/aborted "
            "transitions `new_reason` is None, so the DB column is cleared. The "
            "in-memory mirror only clears pause_reason for pause states — memory and DB "
            "diverge, post-incident 'why was this paused' context is lost.\n\n## Fix\n"
            "Gate the pauseReason write the same way the in-memory mirror does."
        ),
    },
    {
        "title": "M3 — status/state column drift between save_queue and transition_state",
        "priority": "MEDIUM",
        "description": (
            "## QA finding (code-reviewer MEDIUM)\n\n"
            "`transition_state` validates off `record.state or record.status`; "
            "`save_queue` (and the S4 direct-mutation safety-fallback sites) write only "
            "`record.status`. After a fallback mutation the two columns drift; a later "
            "rehydration validates a transition off a stale column and can wrongly "
            "reject a legal move.\n\n## Fix\n`save_queue` must mirror "
            "`record.state = queue.status.value`."
        ),
    },
    {
        "title": "M4 — detect_exhaustion bare '429'/'529' substrings false-positive",
        "priority": "MEDIUM",
        "description": (
            "## QA finding (code-reviewer MEDIUM)\n\n"
            "`utils/exhaustion_detector.py` `_GENERIC_429_SIGNALS`/`_OVERLOADED_SIGNALS` "
            "contain the bare strings `429`/`529`, matched with plain `in` against 4 KB "
            "of subprocess output. Any file path / line number / SHA fragment "
            "containing 429 (e.g. `Foo.tsx:429`) triggers a false exhaustion "
            "classification -> queue wrongly paused into WAITING_RESET.\n\n## Fix\n"
            "Anchor to HTTP-status context (`\\b429\\b` with status keyword) or remove "
            "the bare numeric substrings — the JSON/HTTP-status paths already catch the "
            "real signal."
        ),
    },
    {
        "title": "M5 — reset-failed-tasks rate limit keyed per-IP not per-queue/principal",
        "priority": "MEDIUM",
        "description": (
            "## QA finding (security MEDIUM)\n\n"
            "`api/execution.py:~1462` `@limiter.limit('5/minute')` keys on client IP. "
            "Behind the local proxy callers share an IP — one abuser exhausts the "
            "budget for everyone; a distributed caller bypasses it.\n\n## Fix\n"
            "Key the limiter on `queue_id` or the authenticated principal."
        ),
    },
]


def main():
    created = []
    for b in BUGS:
        issue = post(
            f"/projects/{PROJECT}/issues",
            {
                "title": b["title"],
                "description": b["description"],
                "type": "BUG",
                "priority": b["priority"],
                "parentId": CB2793,
                "labels": LABEL,
                "reporter": "AI",
            },
        )
        created.append((issue.get("key"), b["title"]))
        print(f"created {issue.get('key')}  {b['title']}")

    # Re-rank the two prior security follow-ups: QA escalated both to HIGH.
    for key, iid in (("CB-2801", CB2801), ("CB-2802", CB2802)):
        patch(f"/issues/{iid}", {"priority": "HIGH"})
        print(f"re-ranked {key} -> HIGH")

    print("\n--- summary ---")
    for k, t in created:
        print(f"  {k}: {t}")


if __name__ == "__main__":
    main()
