"""
Database Models for ProjectsManagerWebV2
"""

from models.database import Base, get_db, init_db, AsyncSessionLocal, engine
from models.issue import Issue, Comment, Activity, IssueLink, IssueSequence, Project
from models.grouping import IssueGroup, IssueGroupMember, next_member_position
from models.git import CommitLink, GitSyncState
from models.qa import QATask, QATaskIssueLink, QASequence, QASettings
from models.documentation import ExecutionSummary, FeatureDocumentation, ImplementationNote
from models.doc_settings import DocSettings, SINGLETON_KEY as DOC_SETTINGS_SINGLETON_KEY
from models.agent_registry import AgentProfile
from models.skill_registry import SkillProfile
from models.pipeline import PipelineExecution, PipelineStage, PipelineConfig
from models.park import ParkEvent
from models.autopilot import AutoPilotQueueRecord, AutoPilotTaskRecord, AutoPilotEvent
from models.schemas import (
    IssueType,
    IssueStatus,
    Priority,
    LinkType,
    Complexity,
    IssueBase,
    IssueCreate,
    IssueUpdate,
    IssueResponse,
    IssueWithChildren,
    CommentBase,
    CommentCreate,
    CommentResponse,
    ActivityResponse,
    IssueLinkCreate,
    IssueLinkResponse,
    IssueLinkBulkCreate,
    IssueLinkBulkSkipped,
    IssueLinkBulkResponse,
    IssueLinkDeleteResponse,
    IssueRelationsListResponse,
    IssueSummary,
    IssueGroupCreate,
    IssueGroupUpdate,
    IssueGroupResponse,
    IssueGroupMemberResponse,
    GroupAggregateStatus,
    IssueGroupDetailResponse,
    PaginatedGroupResponse,
    IssueGroupMembersBulkAdd,
    IssueGroupMembersBulkAddResponse,
    IssueGroupMembersBulkRemove,
    IssueGroupMembersBulkRemoveResponse,
    IssueGroupMembersReorder,
    IssueGroupMembersReorderResponse,
    ProjectResponse,
    PaginatedResponse,
    BatchStatusUpdate,
    IssueSequenceResponse,
    # QA Board schemas
    QATaskStatus,
    QATaskType,
    QAPriority,
    QATaskBase,
    QATaskCreate,
    QATaskUpdate,
    QATaskResponse,
    QATaskWithIssues,
    QAExecutionRequest,
    QAExecutionResult,
    QAPlanGenerateRequest,
    QAPlanGenerateResponse,
    QASettingsUpdate,
    QASettingsResponse,
    QASummary,
    # Documentation schemas
    ExecutionSummaryCreate,
    ExecutionSummaryResponse,
    ExecutionSummaryWithKeyResponse,
    FeatureDocumentationCreate,
    FeatureDocumentationUpdate,
    FeatureDocumentationResponse,
    NoteCategory,
    NoteImportance,
    ImplementationNoteCreate,
    ImplementationNoteResponse,
    DocSettingsResponse,
    DocSettingsUpdate,
)
from models.pipeline_schemas import (
    PipelineStatus,
    StageStatus,
    StageName,
    PipelineExecutionCreate,
    PipelineExecutionUpdate,
    PipelineExecutionResponse,
    PipelineExecutionSummary,
    PipelineStageResponse,
    PipelineConfigCreate,
    PipelineConfigUpdate,
    PipelineConfigResponse,
)
# AutoPilot persistence schemas (CB-1951)
from models.schemas import (
    AutoPilotQueueStatus,
    AutoPilotTaskStatus,
    AutoPilotPauseReason,
    AutoPilotEventType,
    AutoPilotTaskRecordResponse,
    AutoPilotEventResponse,
    AutoPilotQueueRecordResponse,
    AutoPilotRecoveryStatusResponse,
    AutoPilotMetricsResponse,
)

__all__ = [
    # Database
    "Base",
    "get_db",
    "init_db",
    "AsyncSessionLocal",
    "engine",
    # SQLAlchemy Models - Issues
    "Issue",
    "Comment",
    "Activity",
    "IssueLink",
    "IssueGroup",
    "IssueGroupMember",
    "next_member_position",
    "IssueSequence",
    "Project",
    "CommitLink",
    "GitSyncState",
    # SQLAlchemy Models - QA Board
    "QATask",
    "QATaskIssueLink",
    "QASequence",
    "QASettings",
    # SQLAlchemy Models - Documentation
    "ExecutionSummary",
    "FeatureDocumentation",
    "ImplementationNote",
    # SQLAlchemy Models - Agent Registry
    "AgentProfile",
    # SQLAlchemy Models - Skill Registry
    "SkillProfile",
    # SQLAlchemy Models - Pipeline
    "PipelineExecution",
    "PipelineStage",
    "PipelineConfig",
    # SQLAlchemy Models - Park
    "ParkEvent",
    # SQLAlchemy Models - AutoPilot Persistence (CB-1951)
    "AutoPilotQueueRecord",
    "AutoPilotTaskRecord",
    "AutoPilotEvent",
    # Enums - Issues
    "IssueType",
    "IssueStatus",
    "Priority",
    "LinkType",
    "Complexity",
    # Enums - QA Board
    "QATaskStatus",
    "QATaskType",
    "QAPriority",
    # Enums - Pipeline
    "PipelineStatus",
    "StageStatus",
    "StageName",
    # Pydantic Schemas - Issues
    "IssueBase",
    "IssueCreate",
    "IssueUpdate",
    "IssueResponse",
    "IssueWithChildren",
    "CommentBase",
    "CommentCreate",
    "CommentResponse",
    "ActivityResponse",
    "IssueLinkCreate",
    "IssueLinkResponse",
    "IssueLinkBulkCreate",
    "IssueLinkBulkSkipped",
    "IssueLinkBulkResponse",
    "IssueLinkDeleteResponse",
    "IssueRelationsListResponse",
    "IssueSummary",
    "IssueGroupCreate",
    "IssueGroupUpdate",
    "IssueGroupResponse",
    "IssueGroupMemberResponse",
    "GroupAggregateStatus",
    "IssueGroupDetailResponse",
    "PaginatedGroupResponse",
    "IssueGroupMembersBulkAdd",
    "IssueGroupMembersBulkAddResponse",
    "IssueGroupMembersBulkRemove",
    "IssueGroupMembersBulkRemoveResponse",
    "IssueGroupMembersReorder",
    "IssueGroupMembersReorderResponse",
    "ProjectResponse",
    "PaginatedResponse",
    "BatchStatusUpdate",
    "IssueSequenceResponse",
    # Pydantic Schemas - QA Board
    "QATaskBase",
    "QATaskCreate",
    "QATaskUpdate",
    "QATaskResponse",
    "QATaskWithIssues",
    "QAExecutionRequest",
    "QAExecutionResult",
    "QAPlanGenerateRequest",
    "QAPlanGenerateResponse",
    "QASettingsUpdate",
    "QASettingsResponse",
    "QASummary",
    # Pydantic Schemas - Documentation
    "ExecutionSummaryCreate",
    "ExecutionSummaryResponse",
    "ExecutionSummaryWithKeyResponse",
    "FeatureDocumentationCreate",
    "FeatureDocumentationUpdate",
    "FeatureDocumentationResponse",
    "NoteCategory",
    "NoteImportance",
    "ImplementationNoteCreate",
    "ImplementationNoteResponse",
    # Documentation Settings
    "DocSettings",
    "DOC_SETTINGS_SINGLETON_KEY",
    "DocSettingsResponse",
    "DocSettingsUpdate",
    # Pydantic Schemas - Pipeline
    "PipelineExecutionCreate",
    "PipelineExecutionUpdate",
    "PipelineExecutionResponse",
    "PipelineExecutionSummary",
    "PipelineStageResponse",
    "PipelineConfigCreate",
    "PipelineConfigUpdate",
    "PipelineConfigResponse",
    # AutoPilot Persistence enums + schemas (CB-1951)
    "AutoPilotQueueStatus",
    "AutoPilotTaskStatus",
    "AutoPilotPauseReason",
    "AutoPilotEventType",
    "AutoPilotTaskRecordResponse",
    "AutoPilotEventResponse",
    "AutoPilotQueueRecordResponse",
    "AutoPilotRecoveryStatusResponse",
    "AutoPilotMetricsResponse",
]
